### ISSUE TITLE
pins set high during initialization

### ISSUE THREAD

**Issue by CrispyPyro** [RobTillaart/MCP23017_RT#29]
Hi Rob,
I'm giving this library a shot and noticed an unexpected behavior. When I call mcp.begin() the pins on the MCP23017 start high. I can reproduce with a simple sketch that just has Wire.begin() and MCP.begin() in setup. This is different than what I've seen in other (heavier) libraries and was curious if this was intentional. Thanks!

**Comment by RobTillaart** [comment]
Thanks for the question,.
Need to dive into the code /data sheet to see why. (And if it was intentional)
Can you give a link to a library that does not showed it?
Thanks

**Comment by RobTillaart** [comment]
In the **begin()** call there are explicit calls to set all pins to INPUT PULLUP.  See .cpp file.
It could be the cause of the blip.

If you comment these two calls, does it still happen?

If so a solution might be to add a parameter to begin() to do these calls conditionally.

**Comment by CrispyPyro** [comment]
My initial "blip" characterization was inaccurate and due to the fact that my initial test sketch set all pins to OUTPUT and LOW as the next step after mcp.begin(). When the sketch is as described above with only mcp.begin(), the pins start high and stay high.

Commenting out the following DOES change the behavior and the pins are not HIGH:
  if (! writeReg(MCP23017_PUR_A, 0xFF)) return false;
  if (! writeReg(MCP23017_PUR_B, 0xFF)) return false;

One thing I noticed both when switching between your library and others (Adafruit is the most recent) AND when switching between your library with these lines commented/uncommented, is that I need to leave everything unpowered for 10-15 seconds for the behavior to change.

Quick circuit overview: I have an N-channel MOSFET with the Gate pin connected to each pin on the MCP23017. Each MOSFET has an LED connected to the Drain and the Source is connected to Ground.

Steps to reproduce:
1. Flash your original library
2. Observe LEDs are lit
3. Comment out the above lines and flash (or flash the Adafruit library)
4. Observe LEDs are lit
5. Unplug for <10 seconds then re-plug
6. Observe LEDs are lit
7. Unplug for >15 seconds then re-plug
8. Observe LEDs are NOT lit

I've tested a few libraries and here's what I found...
Do NOT exhibit the pin-high behavior:
- Adafruit
- IoAbstraction
- https://github.com/wollewald/MCP23017_WE

DO exhibit the pin-high behavior:
- https://github.com/blemasle/arduino-mcp23017

**Comment by RobTillaart** [comment]
@CrispyPyro 

> Commenting out the following DOES change the behavior and the pins are not HIGH:
if (! writeReg(MCP23017_PUR_A, 0xFF)) return false;
if (! writeReg(MCP23017_PUR_B, 0xFF)) return false;

So I have to make those lines conditional.

Q: would that solve the issue enough for you?

----

> One thing I noticed both when switching between your library and others (Adafruit is the most recent) AND when switching between your library with these lines commented/uncommented, is that I need to leave everything unpowered for 10-15 seconds for the behavior to change.

might be due internal capacitors / capacitance in the device and/or wires.
In projects I always use explicit pull up or pull down resistors.

**Comment by RobTillaart** [comment]
@CrispyPyro 

- created a develop branch plus pull request (version 0.6.2)
- added a parameter to **begin(bool pullup)** to make the INPUT PULLUP mode conditional.
- added a minimal example to see the difference.

Can you please verify if the new branch works for you?
Thanks,

**Comment by RobTillaart** [comment]
New develop branch merged

**Comment by CrispyPyro** [comment]
Sorry for the delay in testing/responding. Using the new version and specifying false has changed the behavior and the pins are no longer high after initialization. Thanks!

**Comment by RobTillaart** [comment]
Good to hear it works for you!
