### ISSUE TITLE
writeReg16() always writes 0x01 to GPIOB

### ISSUE THREAD

**Issue by jellewilbrink** [RobTillaart/MCP23017_RT#33]
`writeReg16()` always write 0x01 (i.e. true) to GPIOB.

This can be resolved by using bitwise (&) AND here instead of logical AND (&&): 
https://github.com/RobTillaart/MCP23017_RT/blob/4337fc27655a9a0cd20e70849cbf4413fecc5899/MCP23017.cpp#L759

**Comment by RobTillaart** [comment]
Good catch, looks definitely like a bug.

**Comment by RobTillaart** [comment]
Searched all my libraries to see if same bug is present and yes one same typo.
Will work on it right away!

**Comment by RobTillaart** [comment]
Created a develop branch and PR to bump the version number to 0.7.0

**Comment by RobTillaart** [comment]
PR merged and 0.7.0 released,

again thanks for finding and fixing the bug, really appreciated!

**Comment by jellewilbrink** [comment]
Wow, what a rapid response time! Thank you for these awesome libraries!

**Comment by RobTillaart** [comment]
Bugs have top priority, and if the bug/solution is straightforward, they should just be fixed asap. 
Also fixed similar bug in ACD10 library.
