### ISSUE TITLE
Assign address 0x38

### ISSUE THREAD

**Issue by lbarcella** [RobTillaart/MCP23017_RT#38]
Hi,
  i cannot change the address about chip with the code
`MCP23017 MCP(0x37);`
the chip is ever on address 0x20

_Thank you for your wonderful job_

**Comment by RobTillaart** [comment]
You need to connect the address lines A0, A1 and A2 to set the address in hardware. 
The code should match these address lines.
The address will be in the range 0x20 - 0x27 see table below

If you have a breakout board you might need to solder some patches. 
If you leave the address lines floating I don't know what happens, any address might might be selected.

###  I2C address

0 = GND
1 = Vcc

|  address  |  A2  |  A1  |  A0  |  notes  |
|:----------|:----:|:----:|:----:|:-------:|
|    0x20   |   0  |   0  |   0  |
|    0x21   |   0  |   0  |   1  |
|    0x22   |   0  |   1  |   0  |
|    0x23   |   0  |   1  |   1  |
|    0x24   |   1  |   0  |   0  |
|    0x25   |   1  |   0  |   1  |
|    0x26   |   1  |   1  |   0  |
|    0x27   |   1  |   1  |   1  |


Will add this table in a next release.

![image](https://github.com/user-attachments/assets/8bccd5f6-71ae-47d3-af6a-1000eb9dcdf7)

**Comment by lbarcella** [comment]
Thank you !

**Comment by RobTillaart** [comment]
If this solves your question you may close the issue!
