### ISSUE TITLE
variable DDR can not be used because it is a constant that designate register #104 of esp32

### ISSUE THREAD

**Issue by trimarco232** [RobTillaart/MCP23017_RT#7]
Hi,
W10, platformio, arduino.h

error is :
Compiling .pio\build\esp32doit-devkit-v1\FrameworkArduino\Esp.cpp.o
.pio\libdeps\esp32doit-devkit-v1\MCP23017\MCP23017.cpp:69:9: error: lvalue required as left operand of assignment
     DDR = MCP23017_DDR_B;
             ^

I had to replace DDR with something like DataDirReg, so that it compiles

thanks

**Comment by RobTillaart** [comment]
Thanks for reporting, I look into it today

**Comment by RobTillaart** [comment]
@trimarco232 
Should be solved now in 0.2.1 release - could compile for both AVR and ESP32 now. 
Please verify.

If there are other issues or (generic) functionality missing, please let me know.
